imports:
    - { resource: tables.yml }

services:
    mot.tzv.controller.mot_tzv_main:
        class: mot\tzv\controller\mot_tzv_main
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@ext.manager'
            - '@language'
            - '@pagination'
            - '@path_helper'
            - '@request'
            - '@template'
            - '@user'
            - '@mot.tzv.mot_tzv_events'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%mot.tzv.tables.tourziel%'
            - '%mot.tzv.tables.tourziel_country%'
            - '%mot.tzv.tables.tourziel_region%'
            - '%mot.tzv.tables.tourziel_cats%'
            - '%mot.tzv.tables.tourziel_wlan%'

    mot.tzv.controller.acp:
        class: mot\tzv\controller\mot_tzv_acp
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@ext.manager'
            - '@language'
            - '@pagination'
            - '@request'
            - '@template'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%mot.tzv.tables.tourziel%'
            - '%mot.tzv.tables.tourziel_country%'
            - '%mot.tzv.tables.tourziel_region%'
            - '%mot.tzv.tables.tourziel_cats%'
            - '%mot.tzv.tables.tourziel_wlan%'

    mot.tzv.mot_tzv_events:
        class: mot\tzv\functions\mot_tzv_events
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@path_helper'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%mot.tzv.tables.tourziel%'
            - '%mot.tzv.tables.tourziel_country%'
            - '%mot.tzv.tables.tourziel_region%'
            - '%mot.tzv.tables.tourziel_cats%'
            - '%mot.tzv.tables.tourziel_wlan%'

    mot.tzv.mot_tzv_listener:
        class: mot\tzv\event\mot_tzv_listener
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@ext.manager'
            - '@controller.helper'
            - '@template'
            - '@user'
            - '%mot.tzv.tables.tourziel%'
            - '%mot.tzv.tables.tourziel_country%'
            - '%mot.tzv.tables.tourziel_region%'
        tags:
            - { name: event.listener }
