imports:
    - { resource: tables.yml }

services:
    mot.tzv.controller.mot_tzv_main:
        class: mot\tzv\controller\mot_tzv_main
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@language'
            - '@notification_manager'
            - '@pagination'
            - '@path_helper'
            - '@ext.manager'
            - '@request'
            - '@template'
            - '@user'
            - '@mot.tzv.mot_tzv_events'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%mot.tzv.tables.tourziel%'
            - '%mot.tzv.tables.tourziel_country%'
            - '%mot.tzv.tables.tourziel_region%'
            - '%mot.tzv.tables.tourziel_cats%'
            - '%mot.tzv.tables.tourziel_wlan%'

    mot.tzv.controller.acp:
        class: mot\tzv\controller\mot_tzv_acp
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@ext.manager'
            - '@language'
            - '@pagination'
            - '@request'
            - '@template'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%mot.tzv.tables.tourziel%'
            - '%mot.tzv.tables.tourziel_country%'
            - '%mot.tzv.tables.tourziel_region%'
            - '%mot.tzv.tables.tourziel_cats%'
            - '%mot.tzv.tables.tourziel_wlan%'

    mot.tzv.controller.ucp:
        class: mot\tzv\controller\mot_tzv_ucp
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@language'
            - '@pagination'
            - '@ext.manager'
            - '@request'
            - '@template'
            - '@user'
            - '@mot.tzv.mot_tzv_events'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%mot.tzv.tables.tourziel%'
            - '%mot.tzv.tables.tourziel_country%'
            - '%mot.tzv.tables.tourziel_region%'
            - '%mot.tzv.tables.tourziel_cats%'

    mot.tzv.mot_tzv_events:
        class: mot\tzv\functions\mot_tzv_events
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@path_helper'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%mot.tzv.tables.tourziel%'
            - '%mot.tzv.tables.tourziel_country%'
            - '%mot.tzv.tables.tourziel_region%'
            - '%mot.tzv.tables.tourziel_cats%'
            - '%mot.tzv.tables.tourziel_wlan%'

    mot.tzv.mot_tzv_listener:
        class: mot\tzv\event\mot_tzv_listener
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@ext.manager'
            - '@controller.helper'
            - '@template'
            - '@user'
            - '@mot.tzv.mot_tzv_events'
            - '%mot.tzv.tables.tourziel%'
        tags:
            - { name: event.listener }

    mot.tzv.notification.type.notify_new_tz:
        class: mot\tzv\notification\mot_tzv_new_tz
        parent: notification.type.base
        shared: false
        tags: [{ name: notification.type }]
        calls:
            - [set_user_loader, ['@user_loader']]
            - [set_helper, ['@controller.helper']]

    mot.tzv.notification.type.notify_tz_edited:
        class: mot\tzv\notification\mot_tzv_tz_edited
        parent: notification.type.base
        shared: false
        tags: [{ name: notification.type }]
        calls:
            - [set_user_loader, ['@user_loader']]
            - [set_helper, ['@controller.helper']]

    mot.tzv.notification.type.notify_tz_deleted:
        class: mot\tzv\notification\mot_tzv_tz_deleted
        parent: notification.type.base
        shared: false
        tags: [{ name: notification.type }]
        calls:
            - [set_user_loader, ['@user_loader']]
            - [set_helper, ['@controller.helper']]
